# coding: utf-8

# flake8: noqa

"""
    Swagger Petstore - OpenAPI 3.0

    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)

    The version of the OpenAPI document: 1.0.27
    Contact: apiteam@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.0.1"

# Define package exports
__all__ = [
    "PetApi",
    "StoreApi",
    "UserApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ApiResponse",
    "Category",
    "Order",
    "Pet",
    "Tag",
    "User",
]

# import apis into sdk package
from petstore_client.api.pet_api import PetApi as PetApi
from petstore_client.api.store_api import StoreApi as StoreApi
from petstore_client.api.user_api import UserApi as UserApi

# import ApiClient
from petstore_client.api_response import ApiResponse as ApiResponse
from petstore_client.api_client import ApiClient as ApiClient
from petstore_client.configuration import Configuration as Configuration
from petstore_client.exceptions import OpenApiException as OpenApiException
from petstore_client.exceptions import ApiTypeError as ApiTypeError
from petstore_client.exceptions import ApiValueError as ApiValueError
from petstore_client.exceptions import ApiKeyError as ApiKeyError
from petstore_client.exceptions import ApiAttributeError as ApiAttributeError
from petstore_client.exceptions import ApiException as ApiException

# import models into sdk package
from petstore_client.models.api_response import ApiResponse as ApiResponse
from petstore_client.models.category import Category as Category
from petstore_client.models.order import Order as Order
from petstore_client.models.pet import Pet as Pet
from petstore_client.models.tag import Tag as Tag
from petstore_client.models.user import User as User

